export interface Food {
  FoodID: string;
  'Food Item': string;
  'Edible part': number;
  Ref: string;
  Water: number;
  Ref_1: string;
  Kilojoules: number;
  Ref_2: string;
  Kilocalories: number;
  Ref_3: string;
  Fat: number | string;
  Ref_4: string;
  SatFa: number | string;
  Ref_5: string;
  'C12:0': number;
  Ref_6: string;
  'C14:0': number;
  Ref_7: string;
  'C16:0': number;
  Ref_8: string;
  'C18:0': number;
  Ref_9: string;
  TransFa: number;
  Ref_10: string;
  MuFa: number | string;
  Ref_11: string;
  'C16:1 sum': number;
  Ref_12: string;
  'C18:1 sum': number;
  Ref_13: string;
  PuFa: number | string;
  Ref_14: string;
  'C18:2n-6': number;
  Ref_15: string;
  'C18:3n-3': number;
  Ref_16: string;
  'C20:3n-3': number;
  Ref_17: string;
  'C20:3n-6': number;
  Ref_18: string;
  'C20:4n-3': number;
  Ref_19: string;
  'C20:4n-6': number;
  Ref_20: string;
  'C20:5n-3 (EPA)': number;
  Ref_21: string;
  'C22:5n-3 (DPA)': number;
  Ref_22: string;
  'C22:6n-3 (DHA)': number;
  Ref_23: string;
  'Omega-3': number;
  Ref_24: string;
  'Omega-6': number;
  Ref_25: string;
  Cholesterol: number;
  Ref_26: string;
  Carbo: number;
  Ref_27: string;
  Starch: number;
  Ref_28: string;
  'Mono+Di': number;
  Ref_29: string;
  Sugar: number;
  Ref_30: string;
  'Dietary fibre': number;
  Ref_31: string;
  Protein: number;
  Ref_32: string;
  Salt: number;
  Ref_33: string;
  Alcohol: number;
  Ref_34: string;
  'Vitamin A': number;
  Ref_35: string;
  Retinol: number;
  Ref_36: string;
  'Beta-carotene': number;
  Ref_37: string;
  'Vitamin D': number;
  Ref_38: string;
  'Vitamin E': number;
  Ref_39: string;
  Thiamin: number;
  Ref_40: string;
  Riboflavin: number;
  Ref_41: string;
  Niacin: number;
  Ref_42: string;
  'Vitamin B6': number;
  Ref_43: string;
  Folate: number;
  Ref_44: string;
  'Vitamin B12': number;
  Ref_45: string;
  'Vitamin C': number;
  Ref_46: string;
  Calcium: number;
  Ref_47: string;
  Iron: number;
  Ref_48: string;
  Sodium: number;
  Ref_49: string;
  Potassium: number;
  Ref_50: string;
  Magnesium: number;
  Ref_51: string;
  Zinc: number;
  Ref_52: string;
  Selenium: number;
  Ref_53: string;
  Copper: number;
  Ref_54: string;
  Phosphorus: number;
  Ref_55: string;
  Iodine: number;
  Ref_56: string;
  PPARIndex: number | string;
  SatFaPer: number | string;
  MuFaPer: number | string;
  PuFaPer: number | string;
}
